# permissions for end users to view bindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: binding-viewer-role
rules:
- apiGroups:
  - app.heidrun.bouchaud.org
  resources:
  - bindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - app.heidrun.bouchaud.org
  resources:
  - bindings/status
  verbs:
  - get
