# permissions for end users to edit projectpaths.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: projectpath-editor-role
rules:
- apiGroups:
  - app.heidrun.bouchaud.org
  resources:
  - projectpaths
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.heidrun.bouchaud.org
  resources:
  - projectpaths/status
  verbs:
  - get
