# permissions for end users to edit projectenvironments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: projectenvironment-editor-role
rules:
- apiGroups:
  - app.heidrun.bouchaud.org
  resources:
  - projectenvironments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.heidrun.bouchaud.org
  resources:
  - projectenvironments/status
  verbs:
  - get
