# permissions for end users to edit projects.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: project-editor-role
rules:
- apiGroups:
  - app.heidrun.bouchaud.org
  resources:
  - projects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.heidrun.bouchaud.org
  resources:
  - projects/status
  verbs:
  - get
