# permissions for end users to view projectenvironments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: projectenvironment-viewer-role
rules:
- apiGroups:
  - app.heidrun.bouchaud.org
  resources:
  - projectenvironments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - app.heidrun.bouchaud.org
  resources:
  - projectenvironments/status
  verbs:
  - get
